POST http://localhost:3001/api/notes
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVwaWNtYW45OSIsImlkIjoiNjU3OGIxMThjYWI5MDE0MDU3ZjU0Y2ZiIiwiaWF0IjoxNzAyNDA4NDkwfQ.5QnKze4jqq4WnMKwYGHEEWSmuz2Y4wlIetM4Ul4VddE

{
    "content": "Maukuauthorisoituna",
    "important": true
}