POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVwaWNtYW45OSIsImlkIjoiNjU3OGIxMThjYWI5MDE0MDU3ZjU0Y2ZiIiwiaWF0IjoxNzAyNDA4NjY0fQ.7_rm67dfAjM9DaGmyo949XR1BFR9qI6SXhQPC99chqQ

{
    "content": "Maukuauthorisoituna",
    "important": true
}